# Generated by Django 4.2.5 on 2023-10-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=60, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='last_name')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='create_at')),
                ('update_at', models.DateTimeField(auto_now=True, null=True, verbose_name='update_at')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
